[package]
name = "sg-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "sg"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sg-adapter-code.workspace = true
sg-adapter-hosting.workspace = true
sg-adoption.workspace = true
sg-gitgraph.workspace = true
sg-impact.workspace = true
sg-merge.workspace = true
sg-model.workspace = true
sg-ontology.workspace = true
sg-operation.workspace = true
sg-policy.workspace = true
sg-proposal.workspace = true
sg-query.workspace = true
sg-spec.workspace = true
sg-store.workspace = true
sg-testgraph.workspace = true
sg-validation.workspace = true
